[tool.poetry]
name = "demir"
version = "0.1.0"
description = ""
authors = ["Zelenin Maxim"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.4"
pillow = "^10.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
