# Generated by Django 5.0.4 on 2024-05-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_alter_customuser_login_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.CharField(max_length=255)),
                ('date_end', models.CharField(max_length=255)),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('Создано', 'Created'), ('В обработке', 'In Process'), ('Завершено', 'Completed')], default='Создано', max_length=32)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
