# Generated by Django 5.0.4 on 2024-05-05 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_car_price'),
        ('rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_end',
            field=models.CharField(max_length=255, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_start',
            field=models.CharField(max_length=255, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Создано', 'Created'), ('В обработке', 'In Process'), ('Завершено', 'Completed'), ('Отклонено', 'Refused')], default='Создано', max_length=32, verbose_name='Статус аренды'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='total_price',
            field=models.IntegerField(verbose_name='Цена аренды'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
