# Generated by Django 5.0.4 on 2024-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_options_alter_tag_options_customuser_fio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=30, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passport_details',
            field=models.CharField(max_length=10, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
